deployment:
  tasks:
    - export DEPLOYPATH=/home/bagu2650/public_html/
    - /bin/cp -R templates $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH